function RF = RandomForest(Trees, Leaf, xTrain, yTrain)

RF = TreeBagger(Trees, xTrain', yTrain', ...
    OOBPredictorImportance="on", ...
    Method="regression", ...
    MinLeafSize=Leaf);

end